// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  // modules: [ '@pinia/nuxt'],
  css: ["@/assets/css/main.css", "@/assets/scss/styles.scss"],
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@import "@/assets/scss/variables.scss";',
        },
      },
    },
  },
  app: {
    head: {
      title: "RES-Q",
      meta: [{ charset: "utf-8" }],
      link: [
        {
          rel: "icon",
          type: "image/svg+xml",
          href: "/icon.svg",
        },
      ],
    },
  },
  imports: {
    dirs: ["stores"],
  },
  modules: ["@pinia/nuxt", "@primevue/nuxt-module"],
  primevue: {
    options: {
      // opiones en español
      locale: {
        accept: "Aceptar",
        reject: "Cancelar",
        choose: "Elegir",
        upload: "Subir",
        cancel: "Cancelar",
        dayNames: [
          "Domingo",
          "Lunes",
          "Martes",
          "Miércoles",
          "Jueves",
          "Viernes",
          "Sábado",
        ],
        dayNamesShort: ["Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
        dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
        monthNames: [
          "Enero",
          "Febrero",
          "Marzo",
          "Abril",
          "Mayo",
          "Junio",
          "Julio",
          "Agosto",
          "Septiembre",
          "Octubre",
          "Noviembre",
          "Diciembre",
        ],
        monthNamesShort: [
          "Ene",
          "Feb",
          "Mar",
          "Abr",
          "May",
          "Jun",
          "Jul",
          "Ago",
          "Sep",
          "Oct",
          "Nov",
          "Dic",
        ],
        today: "Hoy",
        weekHeader: "Semana",
        firstDayOfWeek: 1,
        dateFormat: "dd/mm/yy",
        weak: "Débil",
        medium: "Medio",
        strong: "Fuerte",
        passwordPrompt: "Introducir una contraseña",
        emptyFilterMessage: "No se encontraron resultados",
        emptyMessage: "No hay opciones disponibles",
        clear: "Limpiar",
        fileSizeTypes: [
          "Bytes",
          "KB",
          "MB",
          "GB",
          "TB",
          "PB",
          "EB",
          "ZB",
          "YB",
        ],
      },
    },
  },
});
